<?php

namespace Siscourb\User\Fixture;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-06 at 22:19:58.
 */
class RoleFixtureTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RoleFixture
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RoleFixture;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\User\Fixture\RoleFixture::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        $objectManager = \Mockery::mock('Doctrine\Common\Persistence\ObjectManager');
        $objectManager->shouldReceive('persist')->with(\Mockery::any())
            ->andReturn(null)->times(4);
        $objectManager->shouldReceive('flush')->with()->andReturn(null)->times(4);
        
        $fixture = new RoleFixture();
        $fixture->load($objectManager);
    }
}
