<style>
    body {
        padding: 0;
        margin: 0;
    }
    html, body, .container, #map {
        height: 100%;
    }
</style>

<div id="map"></div>
<script src="/js/map.js" type="text/javascript"></script>
<script type="text/javascript">
    $.ajax({
        url: "<?= $this->url('ticket/list/export', ['export' => 'json']) ?>",
        dataType: "json",
        success: function (data) {
            geojsonLayer.addData(data);
        }
    });
    
    map.locate({setView: true, maxZoom: 16});
</script>