<?php

namespace Siscourb\User\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-30 at 22:12:08.
 */
class UserControllerTest extends \PHPUnit_Framework_TestCase
{

    public function testConstruct()
    {
        $this->assertClassHasAttribute('userMapper', 'Siscourb\User\Controller\UserController');
        $this->assertClassHasAttribute('userForm', 'Siscourb\User\Controller\UserController');
    }
    
    public function testIndexPage()
    {
        
    }
}
