<?php

namespace Siscourb\User\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-20 at 18:02:02.
 */
class UserControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var UserController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new UserController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testIndexPage()
    {
        
    }
}
