<?php

namespace Siscourb\Application\Dispatch;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-31 at 01:03:48.
 */
class SiscourbControllerTest extends AbstractHttpControllerTestCase
{

    /**
     * @var SiscourbController
     */
    protected $object;

    public function setUp()
    {
        parent::setUp();
        
        $this->setApplicationConfig(include 'tests/TestConfig.php');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\Application\Controller\SiscourbController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        $this->dispatch('/');
        $this->assertResponseStatusCode(200);
        $this->assertControllerName('Siscourb\Application\Controller\Siscourb');
        $this->assertControllerClass('SiscourbController');
        $this->assertMatchedRouteName('siscourb');
    }

    /**
     * @covers Siscourb\Application\Controller\SiscourbController::aboutAction
     * @todo   Implement testAboutAction().
     */
    public function testAboutAction()
    {
        $this->dispatch('/about');
        $this->assertResponseStatusCode(200);
        $this->assertControllerName('Siscourb\Application\Controller\Siscourb');
        $this->assertControllerClass('SiscourbController');
        $this->assertMatchedRouteName('siscourb/about');
    }
}
