@startuml

title Admin Use Cases

:Admin:

Admin --> (Approve Organization Creation)
Admin --> (Ban Organization)
Admin --> (Ban User)

(Assign User Role) <.. (Approve Organization Creation) :include

Admin --> (Assign User Role)

@enduml
