# .travis.yml
language: php
php:
  - 5.6
  - 5.5
  - 5.4

before_install:
  - composer self-update

install:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c tests/configuration.xml

after_script:
  - php vendor/bin/coveralls -v