@startuml

title User Profile Use Cases

:User:

:Authentication: <<Service>>
:Authorization: <<Service>>

User --> (Login)
User --> (Signup)
User --> (External Signup)
User --> (View Profile)
User --> (Edit Profile)
User --> (Delete Account)
User --> (Logout)

(Login) -- Authentication
(Logout) -- Authentication
(External Signup) -- Authentication

(Edit Profile) -- Authorization
(Delete Account) -- Authorization

note "Serviços internos executados pelos\nmódulos ZfcUser e BjyAuthorize." as N

Authentication . N
N . Authorization

note "A autenticação pode ser provida por um\nserviço externo ou banco de dados." as N2

Authentication .down. N2

@enduml