@startuml

title  Issue Management

:Admin:

Admin --> (Create Category)
Admin --> (Edit Category)
Admin --> (Delete Category)

(Delete Category) ..> (Change Issue Category) :include

Admin --> (Create Issue)
Admin --> (Edit Issue)
Admin --> (Delete Issue)

(Edit Issue) ..> (Change Issue Category) :extends

@enduml