<ul class="nav navbar-nav">
    <?php if ($this->isAllowed('menu', 'menu_user')): ?>
        <li><a href="<?= $this->url('zfcuser/logout'); ?>">Logout</a></li>
        <li><a href="<?= $this->url('zfcuser'); ?>">Perfil</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Chamados <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="<?php echo $this->url('ticket'); ?>">Todos os chamados</a></li>
                <li><a href="<?php echo $this->url('ticket/my-tickets'); ?>">Meus chamados</a></li>
            </ul>
        </li>
    <?php else: ?>
        <li><a href="<?= $this->url('zfcuser/login'); ?>">Login</a></li>
        <li><a href="<?= $this->url('zfcuser/register'); ?>">Cadastrar-se</a></li>
        <li><a href="<?php echo $this->url('ticket'); ?>">Chamados</a></li>
    <?php endif; ?>
    <?php if ($this->isAllowed('menu', 'menu_manager')): ?>
        <li><a href="<?= ''//$this->url('organization');     ?>">Organização</a></li>
    <?php endif; ?>
    <?php if ($this->isAllowed('menu', 'menu_admin')): ?>
        <li><a href="<?= ''//$this->url('admin');     ?>">Admin</a></li>
    <?php endif; ?>
    <li><a href="<?= $this->url('siscourb/about'); ?>">Sobre</a></li>
</ul>
<?php if ($this->isAllowed('menu', 'menu_user')): ?>
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="<?= $this->url('zfcuser'); ?>">
                <i class="glyphicon glyphicon-user"></i>
                Olá, <?= $this->zfcUserIdentity()->getDisplayname() ?>
            </a>
        </li>
    </ul>
<?php endif; ?>