<style>
    .comment-list .row {
        margin-bottom: 0px;
    }
    .comment-list .panel .panel-heading {
        padding: 4px 15px;
        position: absolute;
        border:none;
        /*Panel-heading border radius*/
        border-top-right-radius:0px;
        top: 1px;
    }
    .comment-list .panel .panel-heading.right {
        border-right-width: 0px;
        /*Panel-heading border radius*/
        border-top-left-radius:0px;
        right: 16px;
    }
    .comment-list .panel .panel-heading .panel-body {
        padding-top: 6px;
    }
    .comment-list figcaption {
        /*For wrapping text in thumbnail*/
        word-wrap: break-word;
    }
    /* Portrait tablets and medium desktops */
    @media (min-width: 768px) {
        .comment-list .arrow:after, .comment-list .arrow:before {
            content: "";
            position: absolute;
            width: 0;
            height: 0;
            border-style: solid;
            border-color: transparent;
        }
        .comment-list .panel.arrow.left:after, .comment-list .panel.arrow.left:before {
            border-left: 0;
        }
        /*****Left Arrow*****/
        /*Outline effect style*/
        .comment-list .panel.arrow.left:before {
            left: 0px;
            top: 30px;
            /*Use boarder color of panel*/
            border-right-color: inherit;
            border-width: 16px;
        }
        /*Background color effect*/
        .comment-list .panel.arrow.left:after {
            left: 1px;
            top: 31px;
            /*Change for different outline color*/
            border-right-color: #FFFFFF;
            border-width: 15px;
        }
        /*****Right Arrow*****/
        /*Outline effect style*/
        .comment-list .panel.arrow.right:before {
            right: -16px;
            top: 30px;
            /*Use boarder color of panel*/
            border-left-color: inherit;
            border-width: 16px;
        }
        /*Background color effect*/
        .comment-list .panel.arrow.right:after {
            right: -14px;
            top: 31px;
            /*Change for different outline color*/
            border-left-color: #FFFFFF;
            border-width: 15px;
        }
    }
    .comment-list .comment-post {
        margin-top: 6px;
    }
</style>
<div class="row">
    <div class="col-md-8">
        <h2 class="page-header">Comentários</h2>
        <section class="comment-list">
            <?php foreach ($notes as $note) : ?>
                <article class="row">
                    <div class="col-md-2 col-sm-2 hidden-xs">
                        <figure class="thumbnail">
                            <a href="/user/<?= $note->getUser()->getId() ?>">
                                <?php echo $this->gravatar($note->getUser()->getEmail()) ?>
                                <figcaption class="text-center">
                                    <?=
                                    $this->escapeHtml(
                                        $note->getUser()->getDisplayName()
                                    )
                                    ?>
                                </figcaption>
                            </a>
                        </figure>
                    </div>
                    <div class="col-md-10 col-sm-10">
                        <div class="panel panel-default arrow left">
                            <div class="panel-body">
                                <header class="text-left">
                                    <h3><?=
                                        $this->escapeHtml(
                                            $note->getTitle()
                                        )
                                        ?>
                                    </h3>
                                    <div class="comment-user"><i class="fa fa-user"></i> 
                                        <?=
                                        $this->escapeHtml(
                                            $note->getUser()->getDisplayName()
                                        )
                                        ?>
                                    </div>
                                    <time class="comment-date" datetime="
                                    <?=
                                    $this->dateFormat(
                                        $note->getCreationDate(), IntlDateFormatter::SHORT, // date
                                        IntlDateFormatter::MEDIUM // time
                                    )
                                    ?>
                                          ">
                                        <i class="fa fa-clock-o"></i> 
                                        <?=
                                        $this->dateFormat(
                                            $note->getCreationDate(), IntlDateFormatter::MEDIUM
                                        )
                                        ?>
                                    </time>
                                </header>
                                <div class="comment-post">
                                    <p class="large">
                                        <?=
                                        $this->escapeHtml(
                                            $note->getDescription()
                                        )
                                        ?>
                                    </p>
                                </div>
                                <p class="text-right">
                                    <button type="button"
                                            class="btn btn-default"
                                            data-toggle="modal"
                                            data-title="Responda um comentário."
                                            data-id="<?= $note->getTicket()->getId() ?>"
                                            data-parent-id="<?= $note->getId() ?>"
                                            data-operation="add-note"
                                            data-content="note"
                                            data-target="#mainModal">
                                        <i class="fa fa-reply"></i> reply
                                    </button>
                                </p>
                            </div>
                        </div>
                    </div>
                </article>
            <?php endforeach; ?>
        </section>
    </div>
</div>