<?php

namespace Siscourb\Issue\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-15 at 14:08:22.
 */
class CategoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Category
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Category;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\Issue\Entity\Category::getId
     * @covers Siscourb\Issue\Entity\Category::setId
     */
    public function testGetAndSetId()
    {
        $this->assertAttributeEmpty('id', $this->object);
        $this->assertEmpty($this->object->getId());

        $this->object->setId(1);
        $this->assertEquals(1, $this->object->getId());
    }

    /**
     * @covers Siscourb\Issue\Entity\Category::getName
     * @covers Siscourb\Issue\Entity\Category::setName
     */
    public function testGetAndSetName()
    {
        $this->assertAttributeEmpty('name', $this->object);
        $this->assertEmpty($this->object->getName());

        $expected = 'Street';
        $this->object->setName($expected);
        $this->assertEquals($expected, $this->object->getName());
    }

    /**
     * @covers Siscourb\Issue\Entity\Category::getDescription
     * @covers Siscourb\Issue\Entity\Category::setDescription
     */
    public function testGetAndSetDescription()
    {
        $this->assertAttributeEmpty('description', $this->object);
        $this->assertEmpty($this->object->getDescription());

        $expected = 'Street related issues.';
        $this->object->setDescription($expected);
        $this->assertEquals($expected, $this->object->getDescription());
    }
}
