<?php

namespace Siscourb\Ticket\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-22 at 16:46:58.
 */
class TicketControllerFactoryTest extends \PHPUnit_Framework_TestCase
{

    public function testCreateService()
    {
        $ticketMapper = \Mockery::mock('Siscourb\Ticket\Repository\TicketRepository');

        $serviceLocator = \Mockery::mock('Zend\ServiceManager\ServiceManager');
        $serviceLocator->shouldReceive('get')
            ->with('Siscourb\Ticket\Mapper\TicketMapper')->once()->andReturn($ticketMapper);

        $controllerManager = \Mockery::mock('Zend\Mvc\Controller\ControllerManager');
        $controllerManager->shouldReceive('getServiceLocator')->once()->andReturn($serviceLocator);

        $taskControllerFactory = new TicketControllerFactory();

        $this->assertInstanceOf(
            '\Siscourb\Ticket\Controller\TicketController',
            $taskControllerFactory->createService($controllerManager)
        );
    }
}
