<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SisCoUrb')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php
        echo $this->headLink()
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
        ?>
        
        <style>
            body{
                background-color: #444;
                background: url(http://mymaplist.com/img/parallax/pinlayer2.png),url(http://mymaplist.com/img/parallax/pinlayer1.png),url(http://mymaplist.com/img/parallax/back.png);    
            }

            .vertical-offset-100{
                padding-top:100px;
            }
        </style>

        <!-- Scripts -->
        <script type='text/javascript'>
            $(document).ready(function () {
                $("[data-toggle=tooltip]").tooltip();
            });
        </script>
        <script src="http://mymaplist.com/js/vendor/TweenLite.min.js"></script>
        <!-- This is a very simple parallax effect achieved by simple CSS 3 multiple backgrounds, made by http://twitter.com/msurguy -->
        <?php
        echo $this->headScript()
            ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-2.1.1.min.js')
        ?>
        <script>
            $(document).ready(function () {
                $(document).mousemove(function (e) {
                    TweenLite.to($('body'),
                            .5,
                            {css:
                                        {
                                            backgroundPosition: "" + parseInt(event.pageX / 8) + "px " + parseInt(event.pageY / '12') + "px, " + parseInt(event.pageX / '15') + "px " + parseInt(event.pageY / '15') + "px, " + parseInt(event.pageX / '30') + "px " + parseInt(event.pageY / '30') + "px"
                                        }
                            });
                });
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Abrir Navegação</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('siscourb'); ?>">SisCoUrb</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <?= $this->partial('layout/nav/menu.phtml'); ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat(
                    '<div%s>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                        <ul><li>'
                )->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
            echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>
            <div class="row vertical-offset-100">
                <div class="col-md-4 col-md-offset-4">
                    <div class="panel panel-default">
                        <?= $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>