<?php

namespace Siscourb\User\Form;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-30 at 20:17:29.
 */
class UserFieldsetFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Siscourb\User\Form\UserFieldsetFactory::createService
     */
    public function testCreateService()
    {
        $doctrineManager = \Mockery::mock('Doctrine\Common\Persistence\ObjectManager');
        
        $serviceLocator = \Mockery::mock('Zend\ServiceManager\ServiceManager');
        $serviceLocator->shouldReceive('get')->with('Doctrine\ORM\EntityManager')
                ->once()->andReturn($doctrineManager);
        
        $formManager = \Mockery::mock('Zend\Form\FormElementManager');
        $formManager->shouldReceive('getServiceLocator')->once()->andReturn($serviceLocator);
        
        $userFieldsetFactory = new UserFieldsetFactory();

        $this->assertInstanceOf(
            'Siscourb\User\Form\UserFieldset',
            $userFieldsetFactory->createService($formManager)
        );
    }
}
