<?php

namespace Siscourb\User\Form;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-30 at 20:25:05.
 */
class UserFormFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Siscourb\User\Form\UserFormFactory::createService
     */
    public function testCreateService()
    {
        $userFieldset = \Mockery::mock(new UserFieldset());
        
        $formManager = \Mockery::mock('Zend\Form\FormElementManager');
        $formManager->shouldReceive('get')->with('Siscourb\User\Form\UserFieldset')
                ->andReturn($userFieldset)->once();
        
        $userFormFactory = new UserFormFactory();
        
        $this->assertInstanceOf(
            'Siscourb\User\Form\UserForm',
            $userFormFactory->createService($formManager)
        );
    }
}
