<?php

namespace Siscourb\User\Form;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-30 at 19:54:23.
 */
class UserFormTest extends \PHPUnit_Framework_TestCase
{
    public function testFormConstruction()
    {
        $userFieldset = \Mockery::mock(new UserFieldset());
        
        $userForm = new UserForm($userFieldset);
        
        $this->assertInstanceOf('Siscourb\User\Form\UserForm', $userForm);
        $this->assertInstanceOf('Zend\Form\Fieldset', $userForm->get('User'));
        $this->assertInstanceOf('Zend\Form\Element\Submit', $userForm->get('submit'));
        $this->assertEquals($userForm->getAttribute('method'), 'post');
        $this->assertEquals($userForm->getBaseFieldset(), $userFieldset);
    }
}
