<?php

namespace Siscourb\Ticket\Entity;

use PHPUnit_Framework_TestCase;
use Siscourb\Ticket\ValueObject\Point;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-15 at 21:17:34.
 */
class LocationTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Location
     */
    protected $location;

    /**
     *
     * @var Point
     */
    protected $point;

    /**
     *
     * @var string
     */
    protected $address;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->point = new Point(-23.550389, -46.633973);
        $this->address = 'Marco zero de São Paulo - Praça da Sé';
        $this->location = new Location($this->point, $this->address);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\Ticket\Entity\Location::__construct
     */
    public function testConstructParams()
    {
        $this->assertAttributeSame($this->point, 'point', $this->location);
        $this->assertAttributeSame($this->address, 'address', $this->location);
    }

    /**
     * @covers Siscourb\Ticket\Entity\Location::getPoint
     */
    public function testGetPoint()
    {
        $this->assertSame($this->point, $this->location->getPoint());
    }

    /**
     * @covers Siscourb\Ticket\Entity\Location::getAddress
     */
    public function testGetAddress()
    {
        $this->assertSame($this->address, $this->location->getAddress());
    }
}
