<?php

namespace Siscourb\User\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-01 at 14:24:48.
 */
class RoleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Role
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Role;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testGetAndSetId()
    {
        $this->assertEmpty($this->object->getId());
        
        $this->object->setId(3);
        $this->assertEquals(3, $this->object->getId());
    }

    public function testGetAndSetRoleId()
    {
        $this->assertEmpty($this->object->getRoleId());
        
        $this->object->setRoleId('guest');
        $this->assertEquals('guest', $this->object->getRoleId());
        
        $this->object->setRoleId('user');
        $this->assertEquals('user', $this->object->getRoleId());
    }

    public function testGetAndSetParent()
    {
        $role = \Mockery::mock(new Role());
        $role->setId(1);
        $role->setRoleId('guest');
        
        $this->object->setParent($role);
        $this->assertSame($role, $this->object->getParent());
        
        $role2 = \Mockery::mock(new Role());
        $role2->setId(2);
        $role2->setRoleId('user');
        
        $this->object->setParent($role2);
        $this->assertSame($role2, $this->object->getParent());
    }
}
