<?php

namespace Siscourb\User\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-20 at 16:58:55.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testClassAttributes()
    {
        $this->assertObjectHasAttribute('id', $this->object);
        $this->assertObjectHasAttribute('name', $this->object);
        $this->assertObjectHasAttribute('email', $this->object);
        $this->assertObjectHasAttribute('password', $this->object);
    }

    public function testSetAndGetId()
    {
        $this->assertNull($this->object->getId());
        
        $this->object->setId(1);
        $this->assertSame(1, $this->object->getId());
    }
    
    public function testSetAndGetName()
    {
        $this->assertNull($this->object->getName());
        
        $this->object->setName('John');
        $this->assertSame('John', $this->object->getName());
    }
    
    public function testSetAndGetEmail()
    {
        $this->assertNull($this->object->getEmail());
        
        $this->object->setEmail('john@john.com');
        $this->assertSame('john@john.com', $this->object->getEmail());
    }
    
    public function testSetAndGetPassword()
    {
        $this->object->setPassword('12345');
        
        $this->assertTrue(password_verify('12345', $this->object->getPassword()));
    }
}
