<?php

namespace Siscourb\User\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-03-20 at 16:58:55.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testClassAttributes()
    {
        $this->assertObjectHasAttribute('id', $this->object);
        $this->assertObjectHasAttribute('name', $this->object);
        $this->assertObjectHasAttribute('email', $this->object);
        $this->assertObjectHasAttribute('password', $this->object);
    }
}
