<?php

namespace Siscourb\Contribute\Controller;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-28 at 13:43:53.
 */
class ContributeControllerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ContributeController
     */
    protected $contributeController;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->contributeController = new ContributeController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\Contribute\Controller\ContributeController::indexAction
     * @todo   Implement testIndexAction().
     */
    public function testIndexAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Siscourb\Contribute\Controller\ContributeController::sendMessageAction
     * @todo   Implement testSendMessageAction().
     */
    public function testSendMessageAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Siscourb\Contribute\Controller\ContributeController::confirmationAction
     * @todo   Implement testConfirmationAction().
     */
    public function testConfirmationAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
