@startuml

title User->Organization Use Cases

:User:

User --> (Organization list)
User --> (Organization resume)
(Organization resume) ..> (Organization Rate) :extends

User --> (Create Organization Request)
note left of (Create Organization Request) :An Administrator will approve the establishment of the Organization
(Create Organization Request) ..> (Inform Request) :includes
note left of (Inform Request) :Reports the Admin on the establishment of the organization
(Create Organization Request) ...> (Inform Approval) :includes
note left of (Inform Approval) :Email User due waiting on approval

@enduml