<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SisCoUrb')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no') ?>

        <?php
        echo $this->headLink()
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
            ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css')
            ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css')
            ->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css')
            ->prependStylesheet('http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css')
            ->prependStylesheet('//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
            ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.min.js')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js')
            ->prependFile('http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js')
            ->prependFile('//code.jquery.com/ui/1.11.4/jquery-ui.min.js')
            ->prependFile('//code.jquery.com/jquery-2.1.1.min.js')
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.js');
        ?>

        <script type='text/javascript'>
            $(document).ready(function () {
                $("[data-toggle=tooltip]").tooltip();
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Abrir Navegação</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('siscourb'); ?>">SisCoUrb</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <?= $this->partial('nav/menu.phtml'); ?>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php
            $flash = $this->flashMessenger();
            $flash->setMessageOpenFormat(
                    '<div%s>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                        <ul><li>'
                )->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
            echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
            echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
            echo $flash->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
            echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
            ?>
            <?= $this->content; ?>
        </div>
    </body>
</html>