<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SisCoUrb')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink()
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
            ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
            ->prependFile('//code.jquery.com/jquery-2.1.1.min.js') ?>

        <script type='text/javascript'>
            $(document).ready(function () {
                $("[data-toggle=tooltip]").tooltip();
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Abrir Navegação</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('siscourb');?>">SisCoUrb</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        
                        <?php if($this->isAllowed( 'menu', 'menu_user')): ?>
                        <li><a href="<?= $this->url('zfcuser/logout');?>">Logout</a></li>
                        <li><a href="<?= $this->url('zfcuser');?>">Perfil</a></li>
                        <li><a href="<?php //echo $this->url('task');?>">Chamados</a></li>
                        <?php else: ?>
                        <li><a href="<?= $this->url('zfcuser/login');?>">Login</a></li>
                        <li><a href="<?= $this->url('zfcuser/register');?>">Cadastrar-se</a></li>
                        <?php endif;?>
                        <?php if($this->isAllowed( 'menu', 'menu_manager')): ?>
                        <li><a href="<?= ''//$this->url('organization');?>">Organização</a></li>
                        <?php endif;?>
                        <li><a href="<?= $this->url('siscourb/about');?>">Sobre</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
    </body>
</html>