<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('SisCoUrb')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no') ?>

        <?php
        echo $this->headLink()
                ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
                ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
                ->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css')
                ->prependStylesheet('http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
                ->prependFile('//code.jquery.com/jquery-2.1.1.min.js')
                ->prependFile('http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js')
        ?>

        <script type='text/javascript'>
            $(document).ready(function () {
                $("[data-toggle=tooltip]").tooltip();
            });
        </script>
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Abrir Navegação</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('siscourb'); ?>">SisCoUrb</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">

                        <?php if ($this->isAllowed('menu', 'menu_user')): ?>
                            <li><a href="<?= $this->url('zfcuser/logout'); ?>">Logout</a></li>
                            <li><a href="<?= $this->url('zfcuser'); ?>">Perfil</a></li>
                            <li><a href="<?php echo $this->url('ticket'); ?>">Chamados</a></li>
                        <?php else: ?>
                            <li><a href="<?= $this->url('zfcuser/login'); ?>">Login</a></li>
                            <li><a href="<?= $this->url('zfcuser/register'); ?>">Cadastrar-se</a></li>
                        <?php endif; ?>
                        <?php if ($this->isAllowed('menu', 'menu_manager')): ?>
                            <li><a href="<?= ''//$this->url('organization');      ?>">Organização</a></li>
                        <?php endif; ?>
                        <li><a href="<?= $this->url('siscourb/about'); ?>">Sobre</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
                <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat(
                        '<div%s>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                            &times;
                        </button>
                        <ul><li>'
                        )->setMessageSeparatorString('</li><li>')
                        ->setMessageCloseString('</li></ul></div>');
                echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
                echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
                echo $flash->render('warning', array('alert', 'alert-dismissible', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
                ?>
            <?= $this->content; ?>
        </div>
    </body>
</html>