<?php

namespace Siscourb\Contribute\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-05-28 at 13:42:01.
 */
class MessageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Message
     */
    protected $message;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->message = new Message;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testConstruction()
    {
        $this->assertAttributeInstanceOf('DateTime', 'creationDate', $this->message);
    }

    /**
     * @covers Siscourb\Contribute\Entity\Message::getId
     * @covers Siscourb\Contribute\Entity\Message::setId
     */
    public function testGetAndSetId()
    {
        $this->assertNull($this->message->getId());

        $this->message->setId(1);
        $this->assertAttributeSame(1, 'id', $this->message);

        $this->assertSame(1, $this->message->getId());
    }

    /**
     * @covers Siscourb\Contribute\Entity\Message::getSubject
     * @covers Siscourb\Contribute\Entity\Message::setSubject
     */
    public function testGetAndSetSubject()
    {
        $this->assertNull($this->message->getSubject());

        $test = 'Test';
        $this->message->setSubject($test);
        $this->assertAttributeSame($test, 'subject', $this->message);

        $this->assertSame($test, $this->message->getSubject());
    }

    /**
     * @covers Siscourb\Contribute\Entity\Message::getMessage
     * @covers Siscourb\Contribute\Entity\Message::setMessage
     */
    public function testGetAndSetMessage()
    {
        $this->assertNull($this->message->getMessage());

        $test = 'Test Message';
        $this->message->setMessage($test);
        $this->assertAttributeSame($test, 'message', $this->message);

        $this->assertSame($test, $this->message->getMessage());
    }

    /**
     * @covers Siscourb\Contribute\Entity\Message::getEmail
     * @covers Siscourb\Contribute\Entity\Message::setEmail
     */
    public function testGetAndSetEmail()
    {
        $this->assertNull($this->message->getEmail());

        $test = 'test@test.com';
        $this->message->setEmail($test);
        $this->assertAttributeSame($test, 'email', $this->message);

        $this->assertSame($test, $this->message->getEmail());
    }

    /**
     * @covers Siscourb\Contribute\Entity\Message::getCreationDate
     */
    public function testGetCreationDate()
    {
        $this->assertInstanceOf('DateTime', $this->message->getCreationDate());
    }
}
