<?php

namespace Siscourb\Group\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-15 at 11:02:15.
 */
class GroupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Group
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Group;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testConstruct()
    {
        $this->assertAttributeInstanceOf(
            'Doctrine\Common\Collections\ArrayCollection',
            'contacts',
            $this->object
        );
    }

    /**
     * @covers Siscourb\Group\Entity\Group::getId
     * @covers Siscourb\Group\Entity\Group::setId
     */
    public function testGetAndSetId()
    {
        $this->assertAttributeEmpty('id', $this->object);
        $this->assertEmpty($this->object->getId());

        $this->object->setId(1);
        $this->assertEquals(1, $this->object->getId());
    }

    /**
     * @covers Siscourb\Group\Entity\Group::getName
     * @covers Siscourb\Group\Entity\Group::setName
     */
    public function testGetName()
    {
        $this->assertAttributeEmpty('name', $this->object);
        $this->assertEmpty($this->object->getName());

        $this->object->setName('Prefeitura');
        $this->assertEquals('Prefeitura', $this->object->getName());
    }
}
