<?php

namespace Siscourb\Ticket\Mapper;

use Doctrine\ORM\Mapping\ClassMetadata;
use DoctrineORMModule\Options\EntityManager;
use Mockery;
use PHPUnit_Framework_TestCase;
use Siscourb\Ticket\Repository\TicketRepository;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-22 at 16:54:52.
 */
class TicketMapperFactoryTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var EntityManager
     */
    protected $entityManager;

    /**
     * @var TicketRepository
     */
    protected $ticketRepository;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->entityManager = Mockery::mock('Doctrine\ORM\EntityManager');
        $metadata = new ClassMetadata('Siscourb\Ticket\Entity\Ticket');

        $this->ticketRepository = new TicketRepository($this->entityManager, $metadata);
    }
    
    /**
     * @covers Siscourb\Ticket\Mapper\TicketMapperFactory::createService
     */
    public function testCreateService()
    {
        $this->entityManager->shouldReceive('getRepository')
                ->once()->andReturn($this->ticketRepository);
        
        $serviceManager = Mockery::mock('Zend\ServiceManager\ServiceManager');
        $serviceManager->shouldReceive('get')
                ->with('Doctrine\ORM\EntityManager')
                ->once()->andReturn($this->entityManager);
        
        $ticketMapperFactory = new TicketMapperFactory;

        $this->assertInstanceOf(
            'Siscourb\Ticket\Mapper\TicketMapperInterface',
            $ticketMapperFactory->createService($serviceManager)
        );
    }
}
