<?php

namespace Siscourb\Ticket\Form;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 13:35:47.
 */
class LocationFieldsetFactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var LocationFieldsetFactory
     */
    protected $locationFieldsetFactory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->locationFieldsetFactory = new LocationFieldsetFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\Ticket\Form\LocationFieldsetFactory::createService
     */
    public function testCreateService()
    {
        $doctrineManager = \Mockery::mock('Doctrine\Common\Persistence\ObjectManager');
        $serviceLocator = \Mockery::mock('Zend\ServiceManager\ServiceManager');
        $serviceLocator->shouldReceive('get')->with('Doctrine\ORM\EntityManager')->once()->andReturn($doctrineManager);
        
        $formManager = \Mockery::mock('Zend\Form\FormElementManager');
        $formManager->shouldReceive('getServiceLocator')->once()->andReturn($serviceLocator);
        
        $this->assertInstanceOf(
            'Siscourb\Ticket\Form\LocationFieldset',
            $this->locationFieldsetFactory->createService($formManager)
        );
    }
}
