<?php

namespace Siscourb\Ticket\Form;

use Mockery;
use PHPUnit_Framework_TestCase;
use Siscourb\Ticket\Entity\Ticket;
use Siscourb\User\Entity\User;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-21 at 18:10:52.
 */
class TicketFormFactoryTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var TicketFormFactory
     */
    protected $ticketFormFactory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->ticketFormFactory = new TicketFormFactory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Siscourb\Ticket\Form\TicketFormFactory::createService
     * @todo Create Tests
     */
    public function testCreateService()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
