<style>
    #map {
        height: 150px;
        width: 100%;
    }
</style>

<div class="row">
    <div class="col-md-5">
        <div id="map"></div>
    </div>

    <div class="col-md-7">
        <h2><?= $this->escapeHtml($ticket->getDescription()) ?></h2>
        <time class="comment-date" datetime="<?=
        $this->dateFormat(
            $ticket->getCreationDate(), IntlDateFormatter::SHORT, // date
            IntlDateFormatter::MEDIUM // time
        )
        ?>">
            <i class="fa fa-clock-o"></i> 
            <?=
            $this->dateFormat(
                $ticket->getCreationDate(), IntlDateFormatter::MEDIUM
            )
            ?>
        </time>
        <div>
            <i class="fa fa-exclamation-circle"></i>
            <?= $this->escapeHtml($ticket->getIssue()->getName()) ?>
        </div>
    </div>
</div>

<?php
echo $this->partial('comment/list.phtml', array(
    'notes' => $ticket->getNotes()
));
?>

<?php
echo $this->partial('comment/box.phtml');
?>

<script src="/js/map.js" type="text/javascript"></script>
<script type="text/javascript">
    $.ajax({
        url: "<?= $this->url('ticket/view/export', ['id' => $ticket->getId(), 'export' => 'json']) ?>",
        dataType: "json",
        success: function (data) {
            geojsonLayer.addData(data);
            
            map.addLayer(geojsonLayer);
            map.fitBounds(geojsonLayer.getBounds(),{maxZoom:16});
        }
    });
</script>
