@startuml

title Packages Interaction


package Siscourb{
    package Siscourb.Application

    package Siscourb.User

    package Siscourb.Admin

    package Siscourb.Organization

    package Siscourb.Issue

    package Siscourb.Ticket
}

actor Geoprocessing <<Service>>
actor OAuth <<Service>>

package GeoJson

GeoJson <- Siscourb.Ticket

Geoprocessing -- Siscourb.Application

Siscourb.Application --> Siscourb.Ticket

package Zend

package Doctrine.ORM_Module

package Doctrine

database "SiscourbDB"

Siscourb --> Doctrine :use service

Doctrine --> SiscourbDB

Doctrine <-- Doctrine.ORM_Module
Doctrine.ORM_Module --> Zend

package ZfcUser

package BjyAuthorize

Zend <-- ZfcUser
BjyAuthorize --> ZfcUser :extends

ZfcUser --> Doctrine.ORM_Module
BjyAuthorize --> Doctrine.ORM_Module

Siscourb --> BjyAuthorize :use service
Siscourb.User --> ZfcUser :extends

@enduml