@startuml

title SisCoUrb Use Cases

:Usuário:
:Admin:
:Gestor:
:Autenticador: <<Serviço>>

Usuário <|-- Admin
Usuário <|-- Gestor

Usuário --- (Login)
(Autenticação externa) .> (Login) : extends
(Autenticação externa) -- Autenticador

(Cadastro Externo) .> (Autenticação externa) : includes

Usuário -- (Cadastro de usuário)
Usuário -- (Cadastro Externo)

(Cadastro de usuário) <.(Cadastro de Gestor)  : extends
Usuário -- (Cadastro de Gestor)

Admin -- (Cadastro de Entidade)
Gestor -- (Cadastro de Entidade)

Admin -- (Cadastro de Categorias)
Admin -- (Cadastro de Necessidades)

Usuário -- (Registrar chamado)

@enduml