@startuml

:User:

User -- (Create Ticket)
User -- (List Tickets)
User -- (View Ticket)

(View Ticket) ..> (Add Note) :extends
(View Ticket) ..> (Rate Ticket) :extends
(View Ticket) ..> (Close Ticket) :extends
(View Ticket) ..> (Open Ticket) :extends

@enduml